version: '3.8'
services:
  backend:
    build: backend/.
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - dev.env
    networks:
      - apparatus
  frontend-react:
    build: frontend/react/.
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/react/:/app
      - /app/node_modules
    networks:
      - apparatus
  frontend-svelte:
    build: frontend/svelte/.
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/svelte/:/app
      - /app/node_modules
    networks:
      - apparatus
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=some_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - apparatus
networks:
  apparatus:
